spring:
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/kemao_2?useSSL=false&serverTimezone=CST
      username: kemao_2
      password: 1234
   redis:
      host: 112.74.62.130
      port: 6379
      #数据库只能是0-15，因为目前使用的是默认配置，最多16个数据库
      database: 15
server.port: 8090